### ISSUE TITLE
Can we use other veggies for certification?

### ISSUE THREAD

**Issue by ri0t** [MichaelKreil/blockchain-plus#2]
I feel like, not everyone maybe happy with broccoli. 
...
...
Then again, i just realized, there is no brussel sprout emoji.
Maybe we'll have to ask github to extend the most important missing emojis first.

I hope it's okay that i didn't use an issue template. I used blockchain-plus version 1.2.4.

**Comment by ri0t** [comment]
Oh, and just to be sure, I LOVE THIS PROJECT. Haters gonna hate, but in my opinion, this is one of the best ways to go. Among others, I predicted this! 

Edit: Sorry, i don't want to sound like an expert, apex or know-better, but it was so obvious - yet nobody had the time - unlike @MichaelKreil ..! 

And - probably - even he doesn't have it, yet he still managed to do it (this repo). Thanks man!

**Comment by MichaelKreil** [comment]
I am happy to respond to your point personally.
I've been thinking for a while now about why broccoli, of all things, represents good cyber security. First of all, broccoli is a kind of flower head, which flower head bears fruit / seeds. In IT security, this can be understood as possibility of threats (flora). In general, it is important to understand that behind any "green" of the system hides the potential threat to it. Broccoli is a flower head. Looking at the head, you see the fruit / seeds of this plant. This means that the broccoli too can reproduce and give birth to new "head" (broccoli) with new seeds. The "head" in IT is nothing more than the file system (disk). When it comes to the principle of maintaining security, it is very important to understand that three elements need to be taken into account: confidentiality, integrity and availability. In addition, you should also be aware that it is not up to you what to do with multiple people who work on a single computer.
The second, perhaps, is that the outside of broccoli looks green, and through it we do not know what lies inside. And in IT security it is important to constantly monitor the situation in order to identify threats that have appeared in time. Or just do not miss any new ones.
Although broccoli is a flower, it has a relatively hard woody base. Thus, in IT security, you need to harden your software and hardware so that any attack will be directed at them. Furthermore, broccoli has a unique shape and structure. A combination of different varieties gives "green" an individual taste. Well-known saying "Different strokes for different folks," comes to mind here. In general, diversity is also an important factor in the sustainability of the system itself.
In addition, the broccoli is green, and in IT security it can be used as a «green» penetration testing. Penetration testers are sometimes called "green Hat" (green hat).
Broccoli is grown in the shade, but as soon as it comes out into the sun, he begins to turn green and finally returns to the ground. A huge wave of new opportunities occurs. The same thing happens with our network - under the conditions of protection remain closed inside the company for a long time, but when given an opportunity to enter the world of information exchange and connection with other institutions, they begin to turn green and become less secure.
IT security is probably a tall, thick walls erected around an open space. In this case, the walls, or protection means, perform, among other things, role of "flowers" (which like any plant absorb carbon dioxide, transformed into oxygen). The space behind the powerful wall can be seen as a fertile soil, which will be often watered and fertilized. When planting system in which you are working on install / configure / develop some components (for example - some web-services) it can be said that these components are "seeds". The good thing is that no one knows what exactly will grow up from this.
The second word from the name of this vegetable is "Broccoli" - a young yellow-green flower head of broccoli. In this case cabbage refers to vulnerabilities in the system (a vulnerability is a weak link in a system, and a young flower head is the most vulnerable period for broccoli). This should make you think that when there is no threat, it does not exist at all.
Thanks to the ability to reproduce and spread, broccoli is able to survive in a variety of environments. As a vulnerable "system", it is important to be equipped with effective security protocols to prevent damage.
A Broccoli certificate is a form of certification used to prove authenticity and integrity of the product. However, what is a product? I would like to represent broccoli, which requires authentication. This means that not only does it need to be secure, but also needs to be available for use.
All information you share on Cyber Secure IT is encrypted and stored in a highly secure data center.
Broccoli verified security software is made for both small and large businesses who are interested in offering a safe and secure network to employees, clients and vegetables.
Broccoli provides enterprise-level certificate management solutions based on the modern approach of out-of-band provisioning and multi-tenancy. Broccoli’s single sign-on enables every employee to make their own security decisions, all while ensuring security compliance across all systems. You can rely on Broccoli because its modules are Standalone & multi-tenant, meaning that the cyber attack is very small.
Please upgrade to get more out of our automatic GPT-3 bullshit generator.
I am happy to respond to your point personally.
Thank you for your contribution.
Michael

**Comment by ri0t** [comment]
Ok, that's cool. 

Uh, how do i upgrade? Is a professional edition available?
